### ISSUE TITLE
scrollspy doesn't work on scrolling down 

### ISSUE THREAD

**Issue by Abdullah-Omar** [uikit/uikit#1027]
scrollspy doesn't work on scrolling down 
Ex: 
when the page loaded i scrolled down the animation didn't work
when i reached the end of the page i scrolled up the animation work 
so please what should i do

**Comment by PixelT** [comment]
+1, this same issue...

**Comment by aheinze** [comment]
could you please provide an example on  jsfiddle?

**Comment by malles** [comment]
I think I just came across the same issue for my own new site. Out of the box YOOtheme Aurora. I haven't debugged it yet, but the elements below the viewline already have the `uk-scrollspy-inview` class.
Is it because there is a `100vh` div that makes the target div 'reveal' itself too early?
Scrollspy elements further down the page behave correctly. [demo](http://www.webdemonstratie.nl/)

**Comment by malles** [comment]
I have recreated the issue in some codepens.
Scrollspy triggers too early when a slideshow is above it. Tested in Chrome, IE and FF.
Recreation of the bug: http://codepen.io/malles/pen/ZYjKPx. Best viewed in [iframe](http://s.codepen.io/malles/debug/ZYjKPx) with devtools
Control test; same setup with plain image instead of slideshow: http://codepen.io/malles/pen/ByPZBp [iframe](http://s.codepen.io/malles/debug/ByPZBp?)

**Comment by malles** [comment]
This issue still exists in 2.19, see the codepens. Should be fixed with #1045 but is not...

**Comment by reme101** [comment]
change your doctype to "<!DOCTYPE html>"

**Comment by allpnay** [comment]
reme101, The genius thanks

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team

**Comment by ivanherczeg** [comment]
The issue still exists in UIKit 3

**Comment by janschoenherr** [comment]
@ivanherczeg Please open a seperate issue and add a reproduction link. Thanks.

**Comment by janschoenherr** [comment]
this might have been fixed with the latest version 3.0.0-rc.10? Could you give it a try?

**Comment by ivanherczeg** [comment]
@janschoenherr It turns out, the problem comes in, when we use Angular-Material for Angular 1. 
_Note: It is enough to include the angular-material.css, to trigger the issue._

Please check this six box [CodePen example](https://codepen.io/ivanherczeg/pen/rrKavo)

You can correct the situation, by disabling **height: 100%** or **oveflow:auto** in the scss.

**Comment by nitras** [comment]
Problem is still active. my html requires a body of 100% for a smooth scrollbar. 
Uikit's scrollspy or parallax wont work unless I disable the 100% height.
What is a fix for this please?
