### ISSUE TITLE
upload - dynamic upload path not updated

### ISSUE THREAD

**Issue by psuplat** [uikit/uikit#3076]
Not sure is this is the UIKIT issue or jquery/ajax but my experience with drag'n'drop file uploads is rather limited.

I am building a document section on company intranet, where user can upload document to a selected folder.

each upload link has a data element that contains the path to which the file should be uploaded. clicking the link opens a modal with the upload form

here are:
my form html
```
<input type="hidden"  id="fld-new-file-target" value="">
        <div class="js-upload uk-placeholder uk-text-center">
            <span uk-icon="icon: cloud-upload"></span>
            <span class="uk-text-middle">Upload files by dropping them here or</span>
            <div uk-form-custom>
                <input type="file" multiple>
                <span class="uk-link">selecting one</span>
            </div>
        </div>
        <progress id="js-progressbar" class="uk-progress" value="0" max="100" hidden></progress>
```

example of trigerring link (notice the data-parent)
`<a href="#modal-upload-file" class="add-file"   data-parent="./documents/IT/Policies/" uk-toggle><span uk-icon="icon: cloud-upload"></span> Upload New File</a>`

and the click event
```
$(document).on('click','.add-file',function(){

    var file_parent_folder = $(this).data('parent');
    $('#fld-new-file-parent').val(file_parent_folder); //for testing I aslo put the parent directory path into a hidden input field

    var bar = document.getElementById('js-progressbar');

    UIkit.upload('.js-upload', {

        url: '/Documents/uploadFile/',
        multiple: false,
		name: 'file',
        params:{"fld_parent_folder":file_parent_folder}, //here i am passing the parent directory, which comes from 

        beforeSend: function () {
            console.log('beforeSend', arguments);
        },
        beforeAll: function () {
            console.log('beforeAll', arguments);
        },
        load: function () {
            console.log('load', arguments);
        },
        error: function () {
            console.log('error', arguments);
        },
        complete: function () {
            console.log('complete', arguments);
        },

        loadStart: function (e) {
            console.log('loadStart', arguments);

            bar.removeAttribute('hidden');
            bar.max = e.total;
            bar.value = e.loaded;
        },

        progress: function (e) {
            console.log('progress', arguments);

            bar.max = e.total;
            bar.value = e.loaded;
        },

        loadEnd: function (e) {
            console.log('loadEnd', arguments);

            bar.max = e.total;
            bar.value = e.loaded;
        },

        completeAll: function () {
            console.log('completeAll', arguments);

            setTimeout(function () {
                bar.setAttribute('hidden', 'hidden');
            }, 1000);

           alert(file_parent_folder+'\n'+$('#fld-new-file-parent').val()); //alert the passed variable and the contents of the hidden field
        }

    });

});
```

the upload works perfectly fine for the first selected folder, and the final alert shows that the variable passed to the upload function is the same as the content of hidden field
![image](https://user-images.githubusercontent.com/14207860/33737485-326107b2-db8e-11e7-861a-ae7b5ceafc26.png)

Hower if I close the upload modal, and click the upload link under different folder, for example:

`<a href="#modal-upload-file" class="add-file"   data-parent="./documents/IT/Procedures/" uk-toggle><span uk-icon="icon: cloud-upload"></span> Upload New File</a>`

the upload is successful, but the target folder is the same as before and the file is uploaded to the "Policies" directory, not "Procedures". The final alert shows that the data-parent value has been successfully assigned to file_parent_folder variable and the hidden field value set to that variable, however the file_parent_folder inside the upload function still retained the original value
![image](https://user-images.githubusercontent.com/14207860/33737628-bf7f1896-db8e-11e7-9f7d-203712b403cc.png)

is this an actuall issue, am I missing something or have things in wrong place?

**Comment by janschoenherr** [comment]
Thanks, this has been fixed in the development branch. fa81fee8cf396012805a4c139e891a7d858454fb

**Comment by psuplat** [comment]
Just revisited the functionality using rc5 and I still have the same issue. Something tells me that the fix didn't really fixed it.

**Comment by psuplat** [comment]
Ok, try this: https://codepen.io/anon/pen/vrXpBo

Try to drag a file into the file upload (empty txt will do).
Once the upload is done the final alert will contain the value of the input field and if you do the inspection you will also see the posted value is also 1
![image](https://user-images.githubusercontent.com/14207860/41087294-299f5888-6a34-11e8-9e27-7932bf3dd16d.png)
![image](https://user-images.githubusercontent.com/14207860/41087318-38959460-6a34-11e8-95a3-a1e6d3aadb76.png)

now click button 2, and upload the file again. The alert will show 2, but the inspection will show id has not changed
![image](https://user-images.githubusercontent.com/14207860/41087367-614ef338-6a34-11e8-8367-34f13881624d.png)
![image](https://user-images.githubusercontent.com/14207860/41087380-6ae2643e-6a34-11e8-847d-bb235b39393a.png)

I know the reason behind is the fact the value is passed into UKkit.upload at the time the page is rendered. However I am struggling to figure out a way to make it more dynamic. I tried wrapping the whole UIkit.upload into a function with parameter and calling this function on change event for the upload area but no luck.

I am guessing here that in the main js file there must be something that wipes and rebuilds the array of files that are being posted. Maybe there should also be something that wipes and rebuild the params?

**Comment by janschoenherr** [comment]
Okay, from a quick glance at your code, you are initializing the upload component only once. Therefore the value for _post_id_ won't change later on.

**Comment by psuplat** [comment]
Please forgive me if this question seems daft, but how would I (re)initialize the component everytime file are dropped into it?

**Comment by treyallday** [comment]
**SOLUTION**
For anyone wondering, you have to change the URL in the "beforeSend" parameter. 

```
    UIkit.upload('.js-upload', {
        url: 'ORIGINAL URL HERE',
        multiple: true,
        beforeSend: function () {
            var foo= $("#input").val(); ////grab your val here such as folder
            this.url='CHANGE URL HERE'; ///add in your variable here if you need
        },
```
