### ISSUE TITLE
Slideshow "blank" effect it´s back ( beta 40 and  current dev version ).

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#3208]
### UIkit version

3.0.0-beta.40

### Browser
All
### Steps to reproduce
This is an issue that had been resolved, but seems that it´s back.
Swipe or move cursor on the slideshow repeatedly. I put animated gif at to end to see the effect.

### What is actually happening?
Some slides get a weird "blank" effect, i will put two screens videos, one with the problem ( Beta40 ) and the second working perfectly ( Beta35 ).

This happens on pc ( draggin mouse ) and phone ( swiping ).

 Beta 40
![img_3262 trim](https://user-images.githubusercontent.com/5558563/35893713-15507f7e-0b8e-11e8-8d57-009c699dd142.gif)

Beta 35
![img_3263 trim](https://user-images.githubusercontent.com/5558563/35893798-752dffd4-0b8e-11e8-81e5-5938cb4ac9d5.gif)

**Comment by TomS-** [comment]
@zzseba78 I noticed this too, I've been experiencing this since Beta 36.

**Comment by zzseba78** [comment]
Thanks for confirm, i didn´t know what version intruduced this issue back.

**Comment by janschoenherr** [comment]
Could you please add a codepen. Not sure how to reproduce the issue.

**Comment by TomS-** [comment]
@janschoenherr https://codepen.io/anon/pen/VQPYwd
(Chrome)
1. Drag the slider, while it's still fading, drag again.
2. The animation should fade to white then pop back in. 
3. Repeat dragging until you see the effect. 

I would say do the action of you're trying to get through the slider quickly. If you give time for the animation to run through you don't see the problem as often.

**Comment by janschoenherr** [comment]
This is happening only, if there are just two slides, right?

**Comment by zzseba78** [comment]
It happens with more than 2 slides too.

**Comment by TomS-** [comment]
@janschoenherr I've updated the CodePen to have 3 slides, it does still happen but it's much harder to replicate with more than 2 slides.

My theory is if you grab it just as it's fading out, it keeps that as the starting animation, as the previous element doesn't exist underneath the opacity is showing white. Once it triggers animation finished, it puts the active slide at 1 opacity the new slide just seems to "pop" in.

**Comment by janschoenherr** [comment]
Could you test with the latest develop branch? It should be fixed now.

**Comment by TomS-** [comment]
@janschoenherr I'm afraid not, recompiled the develop branch and it's still happening. I've updated the codepen with the new CSS/JS - https://codepen.io/anon/pen/VQPYwd

**Comment by zzseba78** [comment]
With the recompiled file that @TomS- created is still happening.

**Comment by TomS-** [comment]
@zzseba78 please re-open this

**Comment by janschoenherr** [comment]
Could you give https://github.com/uikit/uikit/commit/8fcf696d776f3e8fcf74ad97226f85642ee3fdd5 another try, please?

**Comment by zzseba78** [comment]
Yes of course.

**Comment by zzseba78** [comment]
The problem persist. Please if someone else can confirm this.

**Comment by zzseba78** [comment]
Fixed in Beta 41! Thanks!!
