### ISSUE TITLE
Youtube fullscreen not working inside uk-animation class

### ISSUE THREAD

**Issue by VeriDigital** [uikit/uikit#3558]
**UIkit version**
3.0.0-rc.12

**Browser**
Checked on Firefox (latest)  / Chrome  (latest) / Opera (latest)

**Reproduction Link**
[https://codepen.io/anon/pen/NLpmve](https://codepen.io/anon/pen/NLpmve)

**Explanation**

Youtube fullscreen not working in uk-animation-* class.

for example

```
  <div class="uk-animation-scale-up">
   <iframe src="https://www.youtube-nocookie.com/embed/YE7VzlLtp-4" width="680" height="315" frameborder="0" allowfullscreen uk-responsive uk-video="automute: true"></iframe>
  </div>
```
if remove uk-animation-* class problem solved.

**Why do I need this class with video?**
I have a comment list. It has YouTube cover art inside. These are animated. When you click on the cover image, the image turns into an iframe and the video opens. As a result, the full screen is not working. (sorry my english)

**Comment by VeriDigital** [comment]
ok, i fix problem with this extra css. maybe in the future uikit fix this problem?

```
:-webkit-full-screen-ancestor:not(iframe) {
    animation-fill-mode: none;
	-webkit-animation-fill-mode: none;
}
```
referance: [https://github.com/daneden/animate.css/issues/313#issuecomment-321200086](https://github.com/daneden/animate.css/issues/313#issuecomment-321200086)

**Comment by janschoenherr** [comment]
This seems to be fixed in Chrome.

**Comment by janschoenherr** [comment]
Still an issue in Safari

**Comment by janschoenherr** [comment]
Fixed in Safari too

**Comment by ZTrainWilliams** [comment]
use domEl.requestFullScreen(), still an issue in Chrome v.121.0.6167.185.
