### ISSUE TITLE
Initial filter not working

### ISSUE THREAD

**Issue by AAlfare** [uikit/uikit#3747]
### UIkit version
3.0.3

### Browser
Safari 12.0.3

### Reproduction Link
https://getuikit.com/docs/filter#active-state

### Steps to reproduce
The initial filtering isn't working when setting a filtering option to `uk-active`. It's not working in the documentation either.

### What is Expected?
Filtering the data by the active option

### What is actually happening?
All items are shown

**Comment by aarongerig** [comment]
Resolved by https://github.com/uikit/uikit/commit/30f01f7045d249f9d638ba0a790dfa63fa6232b0

**Comment by JasonHeyburgh** [comment]
I have updated to the latest repo and this issue is still occurring unfortunately.
