### ISSUE TITLE
Parse error in css (3.9.1)

### ISSUE THREAD

**Issue by picov** [uikit/uikit#4536]
line 4346

:root {
  --uk-leader-fill-content: .;
}

**Comment by janschoenherr** [comment]
Fixed with 7665484e173b934b2fc2c913f5842f9d7f642fba, thanks.

**Comment by Orgoth** [comment]
This is still a problem 

downloaded source: [v3.21.5](https://github.com/uikit/uikit/releases/tag/v3.21.5)
created a custom.scss:
```scss
// 1. Your custom variables and variable overwrites.
$global-link-color: #DA7D02;

// 2. Import default variables and available mixins.
@import "variables-theme.scss";
@import "mixins-theme.scss";

// 3. Your custom mixin overwrites.


// 4. Import UIkit.
@import "uikit-theme.scss";
```

then compiled:
```bash
sass custom.scss > ../css/uikit.css
```

result:
```css
/*
 * Pass fill character to JS
 */
:root {
  --uk-leader-fill-content: .;
}
```

variables-theme.scss
```scss
$leader-fill-content: unquote('.') !default;
```

leader.scss
```scss
:root { --uk-leader-fill-content: #{$leader-fill-content}; }
```
