### ISSUE TITLE
uk-sticky crash

### ISSUE THREAD

**Issue by hrjsoft** [uikit/uikit#4696]
hi
after update to uikit-3.15.15 uk-sticky not working....:(

**Comment by janschoenherr** [comment]
Please add a reproduction link or show an example.

**Comment by acesynapse** [comment]
I am having the same issue.
Sites, check https://www.lakewoodlibrary.org/ and https://www.oleanlibrary.org/. 
Tested on Chrome, Firefox, and Edge. No joy.

**Comment by acesynapse** [comment]
I was able to isolate the issue.
[src/js/core/sticky.js] - Lines 212-220,  added in 3.15.15.
Created a pull request #4701 

https://user-images.githubusercontent.com/98050253/208517675-a401e985-87a5-493a-9103-d4b480d54dca.mp4

**Comment by janschoenherr** [comment]
This one is fixed with d68f40509505f0ee0ed1a6c9a6cadf317e044993

**Comment by acesynapse** [comment]
Thank you, this did fix the z-index issue, but the sticky is still broken.

See image below.

https://user-images.githubusercontent.com/98050253/208688171-08241b4b-76ca-418b-b6b2-9b66ab0b878d.mp4

**Comment by janschoenherr** [comment]
There is an `overflow: hidden` on the parent element `#g-page-surround`. That breaks the native `position: sticky`

**Comment by acesynapse** [comment]
Thank you!
That is part of the Gantry Core, and I haven't had any issues with it so I hadn't considered it. I'm going to suggest that as an edit for Gantry.

https://user-images.githubusercontent.com/98050253/208710507-032f8597-deb3-4522-9636-eb3b3b26707e.mp4

**Comment by janschoenherr** [comment]
The next release will fix this. Thanks!
